name: whitehouse-scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  - pip>=23.0.0
  - pip:
    - supabase>=2.3.0
    - python-dotenv>=1.0.0